export const gameSessionSchema = {
  id: String,
  characterId: String,
  name: String,
  difficulty: String,
  ATK: Number,
  shield: Number,
  maxHP: Number,
  luck: Number,
  HP: Number,
  gold: Number,
  level: Number,
  kills: Number,
  deaths: Number,
};
